services:
  - type: web
    name: movie-recommender-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0 --server.maxUploadSize=50
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
      - key: STREAMLIT_SERVER_MAX_UPLOAD_SIZE
        value: 50
      - key: STREAMLIT_SERVER_ENABLE_CORS
        value: false
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: false
    plan: free # Specify the free plan
    autoDeploy: false # Disable auto-deploy to control when changes are deployed
